apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: secure-demo
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - pvc.yaml
  - postgres.yaml
  - redis.yaml
  - api.yaml
  - web.yaml
  - ingress.yaml
  - rbac-readonly.yaml
